variable "namespace" {
  type = string
}

variable "ingress_class_name" {
  type = string
}

# --- routing / TLS ----------------------------------------------------------
variable "app_hostname" {
  type = string
}

variable "enable_www_redirect" {
  type = bool
}

variable "enable_tls" {
  type = bool
}

variable "cluster_issuer" {
  type = string
}

# --- images -----------------------------------------------------------------
variable "image_repo_backend" {
  type = string
}

variable "image_repo_frontend" {
  type = string
}

variable "image_tag" {
  type = string
}

# --- sizing -----------------------------------------------------------------
variable "backend_replicas" {
  type = number
}

variable "frontend_replicas" {
  type = number
}

variable "enable_backend_hpa" {
  type = bool
}

variable "backend_hpa_max_replicas" {
  type = number
}

variable "backend_hpa_cpu_target" {
  type = number
}

# --- postgres ---------------------------------------------------------------
variable "postgres_storage_gb" {
  type = number
}

variable "postgres_storage_class" {
  type = string
}

variable "postgres_user" {
  type = string
}

variable "postgres_db" {
  type = string
}

variable "postgres_password" {
  type      = string
  sensitive = true
}

# --- app config -------------------------------------------------------------
variable "aspnetcore_environment" {
  type = string
}

variable "connection_string" {
  type      = string
  sensitive = true
}

variable "jwt_issuer" {
  type = string
}

variable "jwt_audience" {
  type = string
}

variable "jwt_signing_key" {
  type      = string
  sensitive = true
}

variable "resend_api_key" {
  type      = string
  sensitive = true
}

variable "email_from_address" {
  description = "From header on outgoing mail; may carry a display name (\"Name <addr>\")."
  type        = string
}

variable "email_frontend_base_url" {
  type = string
}

variable "admin_emails" {
  type      = string
  sensitive = true
}

# --- analytics (feature 033 — self-hosted Umami) ----------------------------
variable "umami_image" {
  type = string
}

variable "umami_image_tag" {
  description = "Umami v3 dropped the `postgresql-` prefix and the `v` that 1.x/2.x tags carried, so this is `3.2.0` — `postgresql-v3.2.0` does not exist and fails at pull."
  type        = string
}

variable "umami_replicas" {
  type = number
}

variable "analytics_hostname" {
  description = "Dashboard hostname. Needs a MANUALLY created DNS A record before the first apply, or the HTTP-01 challenge fails. Measurement does not depend on it — that is same-origin on app_hostname."
  type        = string
}

variable "umami_website_id" {
  description = "The tracked website's UUID. Chosen by us and provisioned, not generated by the dashboard, which is what removes the two-phase bootstrap. NOT a secret: it ships in page source. Empty ships no tracker."
  type        = string
}

variable "umami_db_password" {
  type      = string
  sensitive = true
}

variable "umami_app_secret" {
  description = "Signs dashboard session tokens; a shared or default value makes sessions forgeable."
  type        = string
  sensitive   = true
}

variable "umami_admin_password_hash" {
  description = "bcrypt hash ($2a$/$2b$, cost 10) written over Umami's seeded admin account. Umami has no env var for the password. The PLAINTEXT must never reach the repository, tfvars, or Terraform state."
  type        = string
  sensitive   = true
}

# --- registry pull ----------------------------------------------------------
variable "ghcr_username" {
  type = string
}

variable "ghcr_pull_token" {
  type      = string
  sensitive = true
}

variable "tags" {
  type    = map(string)
  default = {}
}
